### ISSUE TITLE
Navmesh needs work

### ISSUE THREAD

**Issue by PhaestusFox** [janhohenheim/foxtrot#173]
the navmeshes need some work, the first and probably most critical to fix is that they go under the stairs into the houses meaning the companion gets stuck if you hug a wall.
![stuck_follower](https://user-images.githubusercontent.com/75610846/220008092-c35eef22-c68a-4965-8064-0c6bcdd6d17d.png)

next is that some of the navmeshes are not lined up properly, this is mostly fine if the companion is near and will just by momentum cross the boundary but result in odd pathing if the player crosses a boundary.

![navemesh_float](https://user-images.githubusercontent.com/75610846/220008271-32e59a5e-7f00-4892-b5b9-716162243608.png)
![boundry_error](https://user-images.githubusercontent.com/75610846/220008287-0bd9a9b0-347f-48c4-82a4-8e6ad83e0286.png)

and finally, the roofs and insides of buildings have navmeshes even tho it is not possible to get there and use them, this could also be why some of the boundary errors happen
![roof_navmesh](https://user-images.githubusercontent.com/75610846/220008920-050c4597-f1ce-4b9b-99b6-4aa71525b843.png)

**Comment by janhohenheim** [comment]
I recently switched from [bevy_pathmesh](https://github.com/vleue/bevy_pathmesh), which requires an explicit navmesh, to [oxidized_navigation](https://github.com/TheGrimsey/oxidized_navigation), which generates the navmesh on its own. This is why the roofs have navmesh islands; that should not be an issue. For the inaccuracies you mentioned, I suspect they are related to this issue I opened a while ago: https://github.com/TheGrimsey/oxidized_navigation/issues/2
Maybe they could be fixed by playing with the [NavMeshSettings](https://github.com/janhohenheim/foxtrot/blob/main/src/movement/navigation.rs#L27) a bit. I'll investigate :)

**Comment by janhohenheim** [comment]
I optimized the navmesh to address your concerns. If the pathfinding continues to go trough buildings, I'd be glad if you could attach a screenshot to the `oxidized_navigation` bug report linked above.
The current version on `main` sometimes takes long paths because the narrow alleyways are too slim for the NPC to fit through. I'll have to fix that in Blender at some point, but it's not too bad :)
