### ISSUE TITLE
Document `bevy_dolly` git dependency

### ISSUE THREAD

**Issue by TimJentzsch** [janhohenheim/foxtrot#250]
We should document why we are using a git dependency for `bevy_dolly` right now so that we can remove it in the future.

**Comment by janhohenheim** [comment]
Fair enough. @BlackPhlox, is there anything blocking a `v0.1.0` release on crates.io?

**Comment by BlackPhlox** [comment]
There's currently three things:
- Reflection, I haven't been able to get reflection work for drivers yet. 
- API, I'm not sure I'm satisfied with the current api, mostly because there's no way to add new rigs at runtime. (I need tjis for bevy_config_cam) 
- Documentation (docs.rs), there's is none yet due to the uncertainty of the current API layout

Due to my limited time I haven't gone around to this yet and thus why no crate is released yet.

**Comment by TimJentzsch** [comment]
Thanks for the info!
I thought we depended on a git commit because of some bug in the currently released version (this was the case for another git dependency), I should have checked crates.io first :)

**Comment by janhohenheim** [comment]
No longer a git dep :)
