### ISSUE TITLE
Use individual GLTF files for the models

### ISSUE THREAD

**Issue by ethereumdegen** [janhohenheim/foxtrot#292]
IMO using a standardized 'ron' file format offers much more flexibility such as using custom scene editors / custom map editors as opposed to being stuck with using blender. Ideally this is the direction that I hope bevy takes, and it is the direction I am taking with my game workflow.  Besides: using a blender level file wont work for my game anyways as it is more open-world.   I need to use a 'ron' file that can define assets which are extremely far away from the player and which are only spawned in / loaded in  as the player goes to that region .

**Comment by janhohenheim** [comment]
There is a slight misunderstanding in terminology here, since there is nothing Blender-specific in the code right now. 
What we need in any case is a file that describes the 3D objects in a scene. I use GLTF files for that.
Then, we need a file that says *where* these objects should be spawned. I decided to use GLTF for that as well. 
Since I'm using GLTF for both the 3D models and the level layout, I decided to use a single GLTF file for this purpose. 

The reason I wanted to switch from a RON based approach is that there was a lot of opinionated code about *how* that RON should look like. For example, I would prefer to define the components in Rust code because of type safety and to keep the RON small, but this means that I cannot easily change components's constants at runtime. Another example is whether the player character should be in the RON, since that would make sense for a game with changing levels such as Doom, but not for an open world game where the player just spawns wherever they last saved the game.

This led me to believe that the best course of action would be to simply the level loading as much as possible such that users can define their own level formats, since that part is too game-specific for a template to handle. However, you are right: currently you cannot spawn e.g. another house. 
The best solution here would in my opinion be to split the GLTF into one that defines only the positions of the objects in relation to the level and then another GLTF per game object. That way, you can easily code whatever RON schema you want that will in turn spawn in objects defined by the individual GLTFs.

Does my explanation make sense to you? Would that be alright?

**Comment by ethereumdegen** [comment]
Yes i already hacked your template to make it work more like the old way —
not load from a gltf but instead from individual models and just fyi i
struggled quite a bit linking animations but i did figure it out eventually
by looking at your old code and adding an old animation linker system.

So i suspect that may be one area of hardship for others .  But it wasnt
too tough to modify otherwise


Thanks

**Comment by ethereumdegen** [comment]
I hope to see bevy come up with a good standard soln but until then a gltf
is ok for templating

**Comment by janhohenheim** [comment]
Yeah, the animation linking is *very* unintuitive in my opinion!

**Comment by janhohenheim** [comment]
There you go, now the individual GLTFs are available again and can be spawned as blueprints. See [bevy_gltf_blueprints](https://github.com/kaosat-dev/Blender_bevy_components_workflow/tree/main/crates/bevy_gltf_blueprints) for more info. I recommend combining it with [spew](https://github.com/janhohenheim/spew/) for spawning stuff dynamically at runtime :)
